import {
  DEFAULT_CODE_CSHARP,
  DEFAULT_CODE_GO,
  DEFAULT_CODE_JAVA,
  DEFAULT_CODE_JS,
  DEFAULT_CODE_PYTHON,
  DEFAULT_CODE_RUBY,
  DEFAULT_CODE_RUST,
  DEFAULT_CODE_SQL,
  DEFAULT_CODE_TS,
} from "./default-codes";
import LANGUAGES from "./languages";

const LANGUAGES_CODES = {
  [LANGUAGES.javascript]: DEFAULT_CODE_JS,
  [LANGUAGES.typescript]: DEFAULT_CODE_TS,
  [LANGUAGES.python]: DEFAULT_CODE_PYTHON,
  [LANGUAGES.java]: DEFAULT_CODE_JAVA,
  [LANGUAGES.csharp]: DEFAULT_CODE_CSHARP,
  [LANGUAGES.ruby]: DEFAULT_CODE_RUBY,
  [LANGUAGES.rust]: DEFAULT_CODE_RUST,
  [LANGUAGES.go]: DEFAULT_CODE_GO,
  [LANGUAGES.sql]: DEFAULT_CODE_SQL,
};

export default LANGUAGES_CODES;
